source 'https://rubygems.org'

gem 'pry'
gem 'rspec'
gem 'activerecord', '~> 6.0.0', require: 'active_record'
gem 'sinatra-activerecord'
gem 'sqlite3', '~>1.4'
gem 'rake'
gem 'database_cleaner'
gem 'require_all'
